Feature: Adding Bucket Name Parameter to Storage Class to Support Bucket Name of Your Choice
majst01/csi-driver-s3 pull request #58
Opened 2021-11-03 19:47 UTC by dmakeroam

I have added bucket name parameter to support config bucket name in storage class to choose bucket name of your choice while mouting

2021-11-03 19:47 UTC, dmakeroam commented
@majst01 Please help to review this

2021-11-04 11:57 UTC, majst01 requested changes

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	bucketName := *s3.bucketName
nilcheck

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	if len(bucketName) != 0 {
if bucketName != ""

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	} else if len(volumeID) == 0 {
no else if please

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	bucketName := *s3.bucketName
nilcheck

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	if len(bucketName) != 0 {
if bucketName !=""

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	} else if len(volumeID) == 0 {
no else if

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/nodeserver.go
> +	bucketName := *s3.bucketName
nilcheck

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/nodeserver.go
> +	if len(bucketName) != 0 {
if bucketName != ""

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/nodeserver.go
> +		return nil, status.Error(codes.InvalidArgument, "Bucket Name missing in request")
this is wrong

2021-11-04 11:57 UTC, majst01 commented on pkg/s3/nodeserver.go
> +	bucketName := *s3.bucketName
nilcheck

2021-11-04 12:55 UTC, dmakeroam commented on pkg/s3/nodeserver.go
> +		return nil, status.Error(codes.InvalidArgument, "Bucket Name missing in request")
Why this is wrong?

2021-11-04 12:55 UTC, dmakeroam commented
@majst01 I fixed my code, please help to review

2021-11-04 13:15 UTC, dmakeroam commented on pkg/s3/nodeserver.go
> +		return nil, status.Error(codes.InvalidArgument, "Bucket Name missing in request")
I tested my code on my side for bucket name mounting and it worked well

2021-11-04 19:21 UTC, majst01 requested changes

2021-11-04 19:21 UTC, majst01 commented on pkg/s3/controllerserver.go
> +		bucketName = *s3.bucketName
this panics if bucketName is nil

2021-11-04 19:21 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	if err != nil {
errcheck should be nearby the err

2021-11-04 19:21 UTC, majst01 commented on pkg/s3/controllerserver.go
> +		return nil, status.Error(codes.InvalidArgument, "Bucket Name missing in request")
error messages should not start with uppercase

2021-11-04 19:21 UTC, majst01 commented on pkg/s3/controllerserver.go
> +		bucketName = *s3.bucketName
see above

2021-11-04 19:21 UTC, majst01 commented on pkg/s3/controllerserver.go
> +	if err != nil {
see above

2021-11-05 09:06 UTC, dmakeroam commented on pkg/s3/controllerserver.go
> +		return nil, status.Error(codes.InvalidArgument, "Bucket Name missing in request")
Done

2021-11-05 09:06 UTC, dmakeroam commented on pkg/s3/controllerserver.go
> +	if err != nil {
Done

2021-11-05 09:06 UTC, dmakeroam commented on pkg/s3/controllerserver.go
> +		bucketName = *s3.bucketName
Done

2021-11-05 09:08 UTC, dmakeroam commented
Done fixed as your reviewed @majst01

2021-11-06 10:04 UTC, majst01 commented
After thinking again, this PR makes not much sense, because with this only one PVC per storageclass is possible. 
What is you exact requirement ?

2021-11-06 15:33 UTC, dmakeroam commented
> After thinking again, this PR makes not much sense, because with this only one PVC per storageclass is possible. What is you exact requirement ?

I would like to mount a S3 to my pod with specific S3 bucket name to align with my customer compliance, it would not be good to name S3 bucket as PVC name for my use case.

2021-11-06 15:47 UTC, majst01 commented
> > After thinking again, this PR makes not much sense, because with this only one PVC per storageclass is possible. What is you exact requirement ?
> 
> @majst01 I would like to mount a S3 to my pod with specific S3 bucket name to align with my customer compliance, it would not be good to name S3 bucket as PVC name for my use case.

But what happens then if you  create a second PVC ??
So with this the general usability is basically gone

2021-11-06 16:19 UTC, dmakeroam commented
> > > After thinking again, this PR makes not much sense, because with this only one PVC per storageclass is possible. What is you exact requirement ?
> > 
> > 
> > @majst01 I would like to mount a S3 to my pod with specific S3 bucket name to align with my customer compliance, it would not be good to name S3 bucket as PVC name for my use case.
> 
> But what happens then if you create a second PVC ?? So with this the general usability is basically gone

For my use case is generally specific, I have a use case that one pod will use one pvc for mounting data in the blob storage like S3 (This app has only replica). Another use case is I use statefulset with blob mounting to get JKS files for Kafka

2021-11-06 16:24 UTC, dmakeroam commented
From your mention "because with this only one PVC per storageclass is possible."

For my Kafka use case, that is statefulset, as the statefulset nature, it will create per pod pvc that is mounting to the same blob using storage class. I think this is possibly possible, because we don't share the pvc

2021-11-06 16:51 UTC, majst01 commented
> From your mention "because with this only one PVC per storageclass is possible."
> 
> @majst01 For my Kafka use case, that is statefulset, as the statefulset nature, it will create per pod pvc that is mounting to the same blob using storage class. I think this is possibly possible, because we don't share the pvc and we just mouting the JKS files (not modifying the blob contents)

Sure, this is the contract of a sts. But the contract of csi is that configuration parameters of a storageclass apply to all PVCs created and with your PR you will never be able to create more than one PVC in the whole cluster with this storageclass. Therefore this PR will not be merged.

2021-11-06 18:04 UTC, dmakeroam commented
> > From your mention "because with this only one PVC per storageclass is possible."
> > @majst01 For my Kafka use case, that is statefulset, as the statefulset nature, it will create per pod pvc that is mounting to the same blob using storage class. I think this is possibly possible, because we don't share the pvc and we just mouting the JKS files (not modifying the blob contents)
> 
> Sure, this is the contract of a sts. But the contract of csi is that configuration parameters of a storageclass apply to all PVCs created and with your PR you will never be able to create more than one PVC in the whole cluster with this storageclass. Therefore this PR will not be merged.

@majst01 How can we change the contract to support multiple PVCs?

2021-11-14 18:13 UTC, closed without merging